---
region: eu
app_path: ../path/to/my/app
app_name: test.apk
test_runner_app: testRunner.apk
platform: android
is_virtual_device: false
virtual_device_name: Android GoogleApi Emulator
virtual_device_platform_version: ['10.0', '11.0']
real_devices: ["device1", "device2"]
test_distribution: class
